version: '3.8'

services:
  ofps-app:
    image: liujia674/jay-ofps-app:latest
    container_name: ofps-app
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=Ofps;User=sa;Password=Passw0rd!@Ofps;TrustServerCertificate=true;
    restart: no
    depends_on:
      - sqlserver
    networks:
      - ofps_app_net
    platform: linux/amd64
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    volumes:
      - D:\development\docker_desktop\data\mssql:/var/opt/mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd!@Ofps
    restart: no
    networks:
      - ofps_app_net
    platform: linux/amd64
networks:
  ofps_app_net:
    driver: bridge
